### ISSUE TITLE
有2秒的延迟处理

### ISSUE THREAD

**Issue by zhangwenzhao** [jike-engineering/Mongo2ES5#13]
可以做到实时吗，今天刚试用了下，感觉还不错，同步上比mongo-connctor慢 有时时间差很多，是配置原因吗？

**Comment by oceanweave** [comment]
ubuntu系统可以使用吗？

**Comment by aliez-ren** [comment]
为了减少数据量大的时候的请求次数，做一些缓冲，牺牲了时间
最大延迟应该在5秒左右，不知道你说的实时是多少

**Comment by zhangwenzhao** [comment]
好的
