### ISSUE TITLE
请教value替换的方法

### ISSUE THREAD

**Issue by hzbnew** [jike-engineering/Mongo2ES5#17]
你们好，感谢你们的付出，我现在正在试用此插件，感觉很实用。
不过有个问题想咨询一下，目前有没有对抽取的数据进行值替换的方法呢，就是把符合条件的值替换成其他的值，比如把时间项中不符合时间格式的值替换成空值，或者丢弃该field呢？如果有的话，如何使用，请指点一下，非常感谢！

**Comment by hzbnew** [comment]
另外请教一下，对于数组类型的值同步，有比较好的方式吗，谢谢！

**Comment by aliez-ren** [comment]
现在没有替换value的功能
数组类型不用做特殊处理吧，es会自动索引数组中的每一个元素

**Comment by hzbnew** [comment]
但我遇到一个问题，在同步形如 {"一":1, "二": { "三":[{"四":1, "五":2}, {"四":3, "五":4}] } } 的数据时，在transform的mapping中做类似如下指定时， "二": { "三":[{"四":1, "五":2}, {"四":3, "五":4}] }  的数据并没有同步到es中，能指导下是什么问题吗？ 谢谢！
    "一": "A"
    "二.三.四": "B.C.D"
    "二.三.五": "B.C.E"

**Comment by hzbnew** [comment]
补充说明： 在extract的projection中也指定了
"一": 1,
"二.三.四": 1,
"二.三.五": 1

**Comment by aliez-ren** [comment]
因为“三”是个数组，所以必须写成“二.三”把数组中的所有元素都同步过来

**Comment by hzbnew** [comment]
谢谢，配置中使用“二.三”确实是可以把数据同步过来的，不过问题是，我需要做字段映射， 需要把原来的 "二"、"三"、"四" 这些key分别映射成 "B"、"C"、"D"，我最近试了在transform的mapping中配置 "二.三[0].四": "B.C[0].D",  "二.三[0].五": "B.C[0].E"可以同步一组，配置两组就可以同步两组，但实现方式显得有点弱，另外对于不定项的处理比较麻烦。
 请问使用插件有比较好的实现方式吗，谢谢！

**Comment by aliez-ren** [comment]
实现不了。。。之后可能会推出一个自定义transform函数的功能

**Comment by hzbnew** [comment]
好的，感谢支持，我会继续关注的。
