### ISSUE TITLE
tail 3小时前的时间如何限制频率

### ISSUE THREAD

**Issue by zhangwenzhao** [jike-engineering/Mongo2ES5#19]
tail 3小时前的数据(数据量很大)报如下错误:

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

<--- Last few GCs --->

  764250 ms: Mark-sweep 1274.1 (1434.2) -> 1274.0 (1434.2) MB, 2383.4 / 0 ms [allocation failure] [GC in old space requested].
  766655 ms: Mark-sweep 1274.0 (1434.2) -> 1274.0 (1434.2) MB, 2404.9 / 0 ms [allocation failure] [GC in old space requested].
  769073 ms: Mark-sweep 1274.0 (1434.2) -> 1274.0 (1434.2) MB, 2418.3 / 0 ms [last resort gc].
  771554 ms: Mark-sweep 1274.0 (1434.2) -> 1273.9 (1434.2) MB, 2480.8 / 0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x19ec2fcc9fa9 <JS Object>
    1: /* anonymous */(aka /* anonymous */) [/root/.nvm/v6.0.0/lib/node_modules/mongo-es/dist/src/processor.js:6] [pc=0x62a4bb3a8d4] (this=0x19ec2fc04189 <undefined>,resolve=0x156d24938489 <JS Function CreateResolvingFunctions.value (SharedFunctionInfo 0x35c5ec268111)>)
    2: arguments adaptor frame: 2->1
    3: new Promise [native promise.js:53] [pc=0x62a4ad90b45] (this=0x19ec2fc041e9 <the ho...

**Comment by tangniyuqi** [comment]
同问

**Comment by aliez-ren** [comment]
https://github.com/jike-engineering/mongo-es#controls

**Comment by fairytail111** [comment]
@zhangwenzhao 
请问，你的这个问题解决了吗？
