### ISSUE TITLE
有更详细的文档吗？ 如支持哪些mongo和ES版本

### ISSUE THREAD

**Issue by zhugw** [jike-engineering/Mongo2ES5#25]
有更详细的文档吗？ 如支持哪些mongo和ES版本

目前也有mongo同步到ES的需求 查mongo太慢了

**Comment by aliez-ren** [comment]
ES是5.X，mongo2.6以上应该都可以

**Comment by bigdong89** [comment]
可以把version compacity 加到README里面吗

**Comment by gy8409** [comment]
ES 7.11 支持吗？
