### ISSUE TITLE
数据更新频繁，数据量大的数据库同步问题

### ISSUE THREAD

**Issue by Ricky-Hao** [jike-engineering/Mongo2ES5#29]
## 主要问题
目前有一个**数据量很大**，**数据更新频繁**的数据库，进行一次`scan`同步需要**2天**以上。但是MongoDB的`oplog`**默认保留24小时**，因此在`scan`同步的时候，如何才能做到不丢数据呢？（例如刚同步完一个文档，这个文档就被更新了）  

* 是要**同时**启用`tail`和`scan`进行同步么？    
* 一个实例同时跑`tail`和`scan`还是两个实例分别跑比较好？  
* `scan`同步完之后，会**自动**转换成`tail`，这时两个`tail`如何处理？（同步完成时间不能确定，就算手动关闭也会有一段双tail的时间）

**Comment by aliez-ren** [comment]
这样就只能在同步开始的时候把oplog转移到其他地方（比如kafka），在scan完之后，读kafka，目前暂不支持

**Comment by Ricky-Hao** [comment]
能否增加个开关，让一个实例在跑完`scan`时候自动退出，而不是自动切换成`tail`？

**Comment by aliez-ren** [comment]
@Ricky-Hao 你可以尝试提个PR
