### ISSUE TITLE
出现报错，不知怎么解决，求助！

### ISSUE THREAD

**Issue by fairytail111** [jike-engineering/Mongo2ES5#35]
@RenzHoly 
![image](https://user-images.githubusercontent.com/47884483/53613993-1b34c880-3c13-11e9-9d75-545257e9d6ef.png)
请问这个报错怎么解决？

**Comment by aliez-ren** [comment]
reduce `elasticsearchBulkSize` & `mongodbReadCapacity`

**Comment by fairytail111** [comment]
@RenzHoly 
![image](https://user-images.githubusercontent.com/47884483/53615406-b11f2200-3c18-11e9-93c0-d82e30eee822.png)
我都已经改的这么小了，还是报这个错
