### ISSUE TITLE
关于oplog的o2字段问题

### ISSUE THREAD

**Issue by Ricky-Hao** [jike-engineering/Mongo2ES5#37]
https://github.com/jike-engineering/mongo-es/blob/d38596447740e6adae4f43ec2417225c08bbe5e6/src/processor.ts#L178
在源码这里指定了o2内元素必须只有一个，而在我的mongos集群中，o2的元素是两个，不知道这里为何会有强制要求呢？
```
o2: { ip: 'xx.xx.xx.xx', _id: 5c65e44c86d1f817c17bxxxx },
```

**Comment by aliez-ren** [comment]
没有遇到过这样的case，mongo是如何设置的？我不清楚什么情况下o2会有两个key

**Comment by Ricky-Hao** [comment]
可能是因为我在集群里用的，然后集群的`shard key`是`hashed`的IP字段。我这里尝试修改之后跑着是没有问题。

**Comment by aliez-ren** [comment]
学习了，可以把你的改动提个pr吗
