### ISSUE TITLE
调试模式不能运行

### ISSUE THREAD

**Issue by tangniyuqi** [jike-engineering/Mongo2ES5#4]
调试模式不能运行 NODE_ENV=dev mongo-es ./config.json
非调试模式正常运行，需要怎么设置吗？

**Comment by aliez-ren** [comment]
贴一下错误信息

**Comment by tangniyuqi** [comment]
@RenzHoly 'NODE_ENV' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by aliez-ren** [comment]
你用的windows吗，自己想办法吧
