### ISSUE TITLE
出现大量的Request Timeout after 30000ms 如何避免呢

### ISSUE THREAD

**Issue by tangniyuqi** [jike-engineering/Mongo2ES5#6]
tail dna.dna_data -> dna_v1.dna_data Request Timeout after 30000ms
tail dna.dna_data -> dna_v1.dna_data Request Timeout after 30000ms
tail dna.dna_data -> dna_v1.dna_data 500
tail dna.dna_data -> dna_v1.dna_data 500
tail dna.dna_data -> dna_v1.dna_data 500
tail dna.dna_data -> dna_v1.dna_data 500
tail dna.dna_data -> dna_v1.dna_data 500
tail dna.dna_data -> dna_v1.dna_data Request Timeout after 30000ms
tail dna.dna_data -> dna_v1.dna_data Request Timeout after 30000ms
tail dna.dna_data -> dna_v1.dna_data Request Timeout after 30000ms
tail dna.dna_data -> dna_v1.dna_data Request Timeout after 30000ms
tail dna.dna_data -> dna_v1.dna_data Request Timeout after 30000ms
tail dna.dna_data -> dna_v1.dna_data Request Timeout after 30000ms
tail dna.dna_data -> dna_v1.dna_data Request Timeout after 30000ms
tail dna.dna_data -> dna_v1.dna_data Request Timeout after 30000ms
tail dna.dna_data -> dna_v1.dna_data Request Timeout after 30000ms
tail dna.dna_data -> dna_v1.dna_data Request Timeout after 30000ms
tail dna.dna_data -> dna_v1.dna_data Request Timeout after 30000ms
tail dna.dna_data -> dna_v1.dna_data Request Timeout after 30000ms
tail dna.dna_data -> dna_v1.dna_data Request Timeout after 30000ms
tail dna.dna_data -> dna_v1.dna_data Request Timeout after 30000ms
tail dna.dna_data -> dna_v1.dna_data Request Timeout after 30000ms
tail dna.dna_data -> dna_v1.dna_data Request Timeout after 30000ms
tail dna.dna_data -> dna_v1.dna_data Request Timeout after 30000ms
tail dna.dna_data -> dna_v1.dna_data Request Timeout after 30000ms
tail dna.dna_data -> dna_v1.dna_data Request Timeout after 30000ms
tail dna.dna_data -> dna_v1.dna_data Request Timeout after 30000ms
tail dna.dna_data -> dna_v1.dna_data Request Timeout after 30000ms
tail dna.dna_data -> dna_v1.dna_data Request Timeout after 30000ms
tail dna.dna_data -> dna_v1.dna_data Request Timeout after 30000ms
tail dna.dna_data -> dna_v1.dna_data Request Timeout after 30000ms
tail dna.dna_data -> dna_v1.dna_data Request Timeout after 30000ms
tail dna.dna_data -> dna_v1.dna_data Request Timeout after 30000ms
tail dna.dna_data -> dna_v1.dna_data Request Timeout after 30000ms
tail dna.dna_data -> dna_v1.dna_data Request Timeout after 30000ms
tail dna.dna_data -> dna_v1.dna_data Request Timeout after 30000ms
tail dna.dna_data -> dna_v1.dna_data Request Timeout after 30000ms
tail dna.dna_data -> dna_v1.dna_data Request Timeout after 30000ms
tail dna.dna_data -> dna_v1.dna_data Request Timeout after 30000ms
tail dna.dna_data -> dna_v1.dna_data Request Timeout after 30000ms
tail dna.dna_data -> dna_v1.dna_data Request Timeout after 30000ms
tail dna.dna_data -> dna_v1.dna_data Request Timeout after 30000ms
tail dna.dna_data -> dna_v1.dna_data Request Timeout after 30000ms
tail dna.dna_data -> dna_v1.dna_data Request Timeout after 30000ms
tail dna.dna_data -> dna_v1.dna_data Request Timeout after 30000ms

**Comment by tangniyuqi** [comment]
已解决不用了

**Comment by jyanchen** [comment]
@tangniyuqi 请问是怎么解决，elasticsearch的requestTimeout, deadTimeout, maxRetries, keepAlive 这些配置我都尝试过了，不是报request time out 就是 socket hang up 或者其他的。谢谢～！

**Comment by tangniyuqi** [comment]
@jyanchen 我问题也还是重复出现了 之前以为搞定了  你解决了吗
